exports.mvp = [
    "Amon Ra",
    "Baphomet",
    "Dark Lord",
    "Doppelganger",
    "Dracula",
    "Drake",
    "Eddga",
    "Evil Snake Lord",
    "Golden Thief Bug",
    "Hatii",
    "Lord of Death",
    "Maya",
    "Mistress",
    "Moonlight Flower",
    "Orc Hero",
    "Orc Lord",
    "Osiris",
    "Pharaoh",
    "Phreeoni",
    "Samurai Specter",
    "Stomry Knight",
    "Tao Gunka",
    "Turtle General"
];
